version: '3'
services:

# stip (apache)
  stip:
    image: seamlesstip/stip
    restart: always
    ports:
     - "443:443"
     - "10000:10000"
     - "10001:10001"
     - "8443:8443"
     - "8444:8444"
    environment:
      MYSQL_DATABASE: s_tip
      MYSQL_USER: stip
      MYSQL_PASSWORD: stip
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: mysql
    command: ["apachectl", "-D", "FOREGROUND"]
    volumes:
      # for Community persistence
      - ./data/rs_community:/opt/s-tip/rs/community
      # for Apache logs
      - ./log/stip:/var/log/apache2
    depends_on:
     - mysql
     - mongo

# mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: s_tip
      MYSQL_USER: stip
      MYSQL_PASSWORD: stip
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      # SQL for initial data
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      # mount dir for DB persistence
      - ./data/mysql_data:/var/lib/mysql
      # conf
      - ./mysql/conf.d:/etc/mysql/conf.d

# mongo
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      # mount dir for DB persistence
      - ./data/mongo_data:/data/db
